INSERT INTO [dbo].[Books] ([BookId], [Title], [AuthorId]) VALUES (1, N'Visual C# 2012', 7)
INSERT INTO [dbo].[Books] ([BookId], [Title], [AuthorId]) VALUES (2, N'Microsoft Visual C# 2015', 8)
INSERT INTO [dbo].[Books] ([BookId], [Title], [AuthorId]) VALUES (3, N'ASP.NET 4 Website', 9)
INSERT INTO [dbo].[Books] ([BookId], [Title], [AuthorId]) VALUES (4, N'Software Testing', 10)
INSERT INTO [dbo].[Books] ([BookId], [Title], [AuthorId]) VALUES (5, N'Learn Java for Web Development', 11)
INSERT INTO [dbo].[Books] ([BookId], [Title], [AuthorId]) VALUES (6, N'Oracle 12c SQL', 12)
INSERT INTO [dbo].[Books] ([BookId], [Title], [AuthorId]) VALUES (7, N'Software Testing with Visual Studio 2010', 13)
INSERT INTO [dbo].[Books] ([BookId], [Title], [AuthorId]) VALUES (8, N'System Analysis And Design', 14)
INSERT INTO [dbo].[Books] ([BookId], [Title], [AuthorId]) VALUES (1009, N'Java How to programming', 7)
INSERT INTO [dbo].[Books] ([BookId], [Title], [AuthorId]) VALUES (1013, N'PL/SQL', 12)
